#ifndef V81C_V8_2_MANAGEDAPPLICATION_LOGFORM_INCLUDED
#define V81C_V8_2_MANAGEDAPPLICATION_LOGFORM_INCLUDED
namespace v81c { namespace v8_2 { namespace managedapplication { namespace logform { 
enum class AutoSaveFormDataInSettings { 
    DontUse, 
    Use, 
    __LAST
};

enum class BWAValue { 
    _true, 
    _false, 
    _auto, 
    __LAST
};

enum class ButtonRepresentation { 
    Text, 
    Picture, 
    PictureAndText, 
    Auto, 
    __LAST
};

enum class CheckBoxType { 
    Auto, 
    CheckBox, 
    Tumbler, 
    __LAST
};

enum class ChoiceButtonRepresentation { 
    Auto, 
    ShowInDropList, 
    ShowInDropListAndInInputField, 
    ShowInInputField, 
    __LAST
};

enum class ChoiceDataGetModeOnInputByString { 
    Directly, 
    Background, 
    __LAST
};

enum class ChoiceHistoryOnInput { 
    Auto, 
    DontUse, 
    __LAST
};

enum class ColumnsGroup { 
    Horizontal, 
    Vertical, 
    InCell, 
    __LAST
};

enum class CurrentRowUse { 
    Use, 
    DontUse, 
    __LAST
};

enum class EditTextUpdate { 
    Auto, 
    DontUse, 
    OnValueChange, 
    __LAST
};

enum class FoldersAndItems { 
    Items, 
    Folders, 
    FoldersAndItems, 
    Auto, 
    __LAST
};

enum class FormBaseFontVariant { 
    Auto, 
    Normal, 
    Compact, 
    __LAST
};

enum class FormChildrenGroup { 
    Horizontal, 
    Vertical, 
    __LAST
};

enum class FormChildrenWidth { 
    Auto, 
    Equal, 
    LeftWide, 
    LeftWidest, 
    LeftNarrow, 
    LeftNarrowest, 
    __LAST
};

enum class FormDateSelectionMode { 
    Single, 
    Multiple, 
    Interval, 
    __LAST
};

enum class FormElementCommandBarLocation { 
    None, 
    Auto, 
    Top, 
    Bottom, 
    __LAST
};

enum class FormElementOrientation { 
    Horizontal, 
    Vertical, 
    __LAST
};

enum class FormElementOrigin { 
    Source, 
    AutoGenerated, 
    AddedFromContext, 
    __LAST
};

enum class FormElementTitleLocation { 
    None, 
    Auto, 
    Left, 
    Top, 
    Right, 
    Bottom, 
    __LAST
};

enum class FormEnterKeyBehavior { 
    ControlNavigation, 
    DefaultButton, 
    __LAST
};

enum class FormFixedInTable { 
    None, 
    Left, 
    Right, 
    __LAST
};

enum class FormPagesRepresentation { 
    None, 
    TabsOnTop, 
    TabsOnBottom, 
    TabsOnLeftHorizontal, 
    TabsOnRightHorizontal, 
    Swipe, 
    __LAST
};

enum class FormProgressBarRepresentation { 
    Smooth, 
    Broken, 
    BrokenTilt, 
    __LAST
};

enum class FormWindowOpeningMode { 
    Independent, 
    LockOwnerWindow, 
    LockWholeInterface, 
    __LAST
};

enum class FullTextSearchOnInputByString { 
    Use, 
    DontUse, 
    __LAST
};

enum class IncompleteItemChoiceMode { 
    OnEnterPressed, 
    OnActivate, 
    __LAST
};

enum class ItemHorizontalAlignment { 
    Left, 
    Center, 
    Right, 
    Auto, 
    __LAST
};

enum class ItemVerticalAlignment { 
    Top, 
    Center, 
    Bottom, 
    Auto, 
    __LAST
};

enum class LogFormElementAdditionKind { 
    SearchStringRepresentation, 
    ViewStatusRepresentation, 
    SearchControl, 
    __LAST
};

enum class LogFormScrollMode { 
    _auto, 
    use, 
    useIfNecessary, 
    __LAST
};

enum class ManagedFormButtonType { 
    CommandBarButton, 
    UsualButton, 
    Hyperlink, 
    __LAST
};

enum class ManagedFormDecorationType { 
    Label, 
    Picture, 
    __LAST
};

enum class ManagedFormFieldType { 
    Default, 
    LabelField, 
    InputField, 
    CheckBoxField, 
    PictureField, 
    RadioButtonField, 
    SpreadsheetDocumentField, 
    TextDocumentField, 
    FormattedDocumentField, 
    PlannerField, 
    CalendarField, 
    PeriodField, 
    ProgressBarField, 
    TrackBarField, 
    ChartField, 
    GanttChartField, 
    DendrogramField, 
    GraphicalSchemaField, 
    HTMLDocumentField, 
    GeographicalSchemaField, 
    __LAST
};

enum class ManagedFormGroupType { 
    CommandBar, 
    Popup, 
    ColumnGroup, 
    Pages, 
    Page, 
    UsualGroup, 
    ButtonGroup, 
    ContextMenu, 
    AutoCommandBar, 
    Navigator, 
    __LAST
};

enum class MarkingStyle { 
    DontShow, 
    TopLeft, 
    BottomRight, 
    BothSides, 
    __LAST
};

enum class MenuElementPlacementArea { 
    mainCmdsLeft, 
    autoCmds, 
    userCmds, 
    mainCmdsRight, 
    __LAST
};

enum class PictureSize { 
    RealSize, 
    Stretch, 
    Proportionally, 
    Tile, 
    AutoSize, 
    __LAST
};

enum class RadioButtonType { 
    Auto, 
    RadioButtons, 
    Tumbler, 
    __LAST
};

enum class RefreshRequestMethod { 
    None, 
    PullFromTop, 
    PullFromBottom, 
    PullFromTopOrBottom, 
    __LAST
};

enum class ReportFormType { 
    Main, 
    Settings, 
    Variant, 
    __LAST
};

enum class RepresentationInContextMenu { 
    None, 
    AdditionalInContextMenu, 
    OnlyInContextMenu, 
    Auto, 
    __LAST
};

enum class SaveFormDataInSettings { 
    DontUse, 
    UseList, 
    __LAST
};

enum class SearchControlLocation { 
    Auto, 
    None, 
    CommandBar, 
    __LAST
};

enum class SearchOnInput { 
    Use, 
    DontUse, 
    Auto, 
    __LAST
};

enum class SearchStringLocation { 
    Auto, 
    None, 
    CommandBar, 
    Top, 
    Bottom, 
    __LAST
};

enum class SearchStringModeOnInputByString { 
    Begin, 
    AnyPart, 
    __LAST
};

enum class SelectionShowMode { 
    WhenActive, 
    Always, 
    __LAST
};

enum class TableFieldEditMode { 
    Directly, 
    Enter, 
    EnterOnInput, 
    __LAST
};

enum class TableInitialListView { 
    Beginning, 
    End, 
    Auto, 
    __LAST
};

enum class TableInitialTreeView { 
    NoExpand, 
    ExpandTopLevel, 
    ExpandAllLevels, 
    __LAST
};

enum class TableRepresentation { 
    List, 
    HierarchicalList, 
    Tree, 
    __LAST
};

enum class TableRowInputMode { 
    EndOfList, 
    EndOfWindow, 
    AfterCurrentRow, 
    BeforeCurrentRow, 
    __LAST
};

enum class TableRowSelectionMode { 
    Cell, 
    Row, 
    __LAST
};

enum class TableScrollBarUse { 
    DontUse, 
    UseAlways, 
    AutoUse, 
    __LAST
};

enum class TableSelectionMode { 
    SingleRow, 
    MultiRow, 
    __LAST
};

enum class TooltipRepresentation { 
    Auto, 
    None, 
    Balloon, 
    Button, 
    ShowAuto, 
    ShowTop, 
    ShowLeft, 
    ShowBottom, 
    ShowRight, 
    __LAST
};

enum class UsualGroupBehavior { 
    Usual, 
    Collapsible, 
    Ballon, 
    __LAST
};

enum class UsualGroupControlRepresentation { 
    TitleHyperlink, 
    Picture, 
    __LAST
};

enum class UsualGroupRepresentation { 
    None, 
    StrongSeparation, 
    WeakSeparation, 
    NormalSeparation, 
    GroupBox, 
    Line, 
    Margin, 
    __LAST
};

enum class VerticalAlign { 
    Top, 
    Bottom, 
    Center, 
    __LAST
};

enum class ViewScalingMode { 
    Auto, 
    Normal, 
    Large, 
    __LAST
};

enum class ViewStatusLocation { 
    Auto, 
    None, 
    Top, 
    Bottom, 
    __LAST
};

enum class WarningOnEditRepresentation { 
    Show, 
    DontShow, 
    Auto, 
    __LAST
};

} } } } 
#endif
